- name: Add ppa for PHP
  apt_repository: repo='ppa:ondrej/php5'

- name: Install required packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-mysql
    - php5-gd
    - php5-intl
    - php5-imagick
    - php5-imap
    - php5-mcrypt
    - php5-memcache
    - php5-ps
    - php5-pspell
    - php5-recode
    - php5-sqlite
    - php5-tidy
    - php5-xmlrpc
    - php5-xsl
    - php5-xcache
    - php-pear
