- name: Setup ubuntu
  remote_user: sorin
  sudo: yes
  hosts: localhost
  roles:
    - { role: common, name: "Sorin Badea", email: "sorin.badea91@gmail.com" }
    - { role: oh-my-zsh , user: root }
    - { role: oh-my-zsh , user: sorin }
    - { role: php-5.5 }
    - { role: nginx-php, wwwuser: sorin }
    - { role: common-development, user: sorin }
    - { role: common-development-ui }
    - { role: common-ui }
