- name: Add keyserver for HHVM
  shell: apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449

- name: Add repository for HHVM
  shell: add-apt-repository "deb http://dl.hhvm.com/ubuntu trusty main"

- name: Install HHVM
  apt: name=hhvm state=latest update_cache=yes
