- name: Install required repositories
  apt_repository: repo={{ item }}
  with_items:
    - ppa:olivier-berten/misc #mysqlworkbench repo
    - ppa:webupd8team/sublime-text-2
    - ppa:webupd8team/atom
    - ppa:gnome-terminator/nightly

- name: Install development tools
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - mysql-workbench
    - sublime-text
    - atom
    - terminator

- name: Download PHPStorm
  get_url: url=http://download.jetbrains.com/webide/PhpStorm-9.0.2.tar.gz dest=/opt/phpstorm.tar.gz

- name: Unarchive PHPStorm
  unarchive: src='/opt/phpstorm.tar.gz' dest=/opt copy=no

- name: Rename PHPStorm location
  shell: mv /opt/PhpStorm* /opt/phpstorm

- name: Add desktop entry
  template: src='jetbrains-phpstorm.desktop' dest=/usr/share/applications/jetbrains-phpstorm.desktop owner=root group=root mode=0644

- name: Remove archive
  file: path=/opt/phpstorm.tar.gz state=absent