- name: Install common required packages
  apt: name={{ item }} state=latest force=yes
  with_items:
    - mc
    - make
    - gcc
    - wget
    - curl
    - zsh
    - htop
    - tar
    - software-properties-common

- name: Install development packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - siege
    - python-setuptools
    - ufw

- name: Install Python PIP
  shell: curl -sL https://bootstrap.pypa.io/get-pip.py | python -

- name: Install GUI Tools
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - qgit
