- name: Install development packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - siege
    - python-setuptools

- name: Install NodeJS ppa
  shell: curl -sL https://deb.nodesource.com/setup | sudo bash -

- name: Install NodeJS
  apt: name=nodejs state=latest update_cache=yes

- name: Add keyserver for HHVM
  shell: apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449

- name: Add repository for HHVM
  shell: add-apt-repository "deb http://dl.hhvm.com/ubuntu trusty main"

- name: Install HHVM
  apt: name=hhvm state=latest update_cache=yes

- name: Install Python PIP
  shell: curl -sL https://bootstrap.pypa.io/get-pip.py | python -
